### ISSUE TITLE
timestamp, frame number

### ISSUE THREAD

**Issue by sprenge** [FredrikAppelros/pcap-reassembler#1]
Hello Fredrik,

I am using your very interesting library to parse http traffic (see below).  I have noticed that the timestamp and number are from the first fragment.  Is it difficult to find back the ts and number of the last fragment which is more representative for a delay measurement ?

Thanks in advance,

Erwin Sprengers

r = PcapReassembler()
messages = r.load_pcap('y.pcap')
for message in messages:
   #do something

**Comment by FredrikAppelros** [comment]
Perhaps the best solution would be to return an ordered list of all the timestamps of the fragments that make up a message instead of just the first or the last fragment?

**Comment by sprenge** [comment]
Indeed, that would the best solution.
Is that something you can add ?  Or can I help ?

**Comment by FredrikAppelros** [comment]
I'd rather maintain backward compatibility so we'll have to add it under some attribute other than `ts`. I've started fiddling around with it a bit, I'll probably have a fix later this week.

**Comment by sprenge** [comment]
Tried it out, work as expected.  Thanks Fredrik, great stuff
